### PR TITLE
fix 1.10.2 not compiling with typescript

### PR DESCRIPTION
**Pull request by 3vorp**
- wrong index file location (moved to src folder, package.json still pointed to project root
- typings placed in wrong namespace (e.g. `firestorm.firestorm.address()` instead of `firestorm.address()`)

### CODE REVIEW

**Review by TheRolfFR — APPROVED** [review]

**Comment by 3vorp** [comment]
I don't have push access so I can't merge this lol, since you've approved it can you merge it at some point? I want to update the API to a more recent version of firestorm and the current issues are making this impossible.

**Comment by TheRolfFR** [comment]
I need to make a version with npm and update version, i'll do it when I can

**Review by TheRolfFR — APPROVED** [review]

**Review by Juknum — COMMENTED** [review]
Please use `unknown` instead of `any`, this will force users to verify it

(you can also add a generic overload like ˋ get<T>(): Promise<T>ˋ to let the user specify the expected return type)

**Comment by Juknum** [comment]
Oh just noticed the messages were noted "1mo" and not "1m" 😅

**Pull request merged**
